#!/bin/sh

# Time period in minutes
TIMEPERIOD=5

# Default unit
UNIT=requests

#NAME=$(basename $0|grep -P -o '(?<=ec2_autoscaling_).*')

#if [ -z "$SCALEGROUP" ]; then
#	echo 'Cannot read scaling group' >&2
#	exit 1
#fi

case $1 in
	config)
		echo "graph_title AWS CloudWatch $METRICNAME $NAMESPACE"
		echo "graph_vlabel $UNIT"
		echo "graph_category $NAMESPACE"
		echo 'current.label current'
		exit 0;;
esac

if [ -z "$JAVA_HOME" ]; then
	JAVA_HOME=$(readlink -f $(which java)|grep -P -o '.*(?=/bin/java)')
fi

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
	echo 'AWS ID not specified. Set env.AWS_ACCESS_KEY_ID' >&2
	exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
	echo 'AWS Secret not specified. Set env.AWS_SECRET_ACCESS_KEY' >&2
	exit 1
fi

if [ ! -x $AWS_CLOUDWATCH_HOME/bin/mon-get-stats ]; then
	echo 'Cannot execute mon-get-stats. Set env.AWS_CLOUDWATCH_HOME' >&2
	exit 1
fi

TMPFILE=$(mktemp)
if [ ! -w $TMPFILE ]; then
	echo "Cannot write to temp file $TMPFILE" >&2
	exit 1
fi

export AWS_CLOUDWATCH_HOME
export JAVA_HOME
$AWS_CLOUDWATCH_HOME/bin/mon-get-stats $METRICNAME -I $AWS_ACCESS_KEY_ID -S $AWS_SECRET_ACCESS_KEY -n $NAMESPACE --dimensions $DIMENSIONS -s Sum --period 60 --start-time $(date --iso-8601=seconds --date="$TIMEPERIOD minutes ago") > $TMPFILE
if [ $? -ne 0 ]; then
	echo 'Failed to run mon-get-stats' >&2
	rm $TMPFILE
	exit 1
fi

CURRENT=$(echo "($(cat $TMPFILE|awk '{print $3}'|tr '\12' '+')0)/$TIMEPERIOD" | bc)

rm $TMPFILE

echo "current.value $CURRENT"

exit 0
