#!/bin/sh

ASNAME=$(basename $0|grep -P -o '(?<=ec2_asnetwork_).*')

DIMENSIONS=AutoScalingGroupName=$ASNAME
NAMESPACE=AWS/EC2

if [ -z "$ASNAME" ]; then
	echo 'Cannot read autoscaling group name' >&2
	exit 1
fi

case $1 in
	config)
		echo "graph_title $ASNAME network traffic"
		echo "graph_vlabel bits in (-) / out (+) per sec"
		echo "graph_category $NAMESPACE"
		echo 'in.label in'
		echo 'out.label out'
		echo 'out.negative in'
		echo 'in.graph no'
		exit 0;;
esac

if [ -z "$JAVA_HOME" ]; then
	JAVA_HOME=$(readlink -f $(which java)|grep -P -o '.*(?=/bin/java)')
fi

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
	echo 'AWS ID not specified. Set env.AWS_ACCESS_KEY_ID' >&2
	exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
	echo 'AWS Secret not specified. Set env.AWS_SECRET_ACCESS_KEY' >&2
	exit 1
fi

if [ ! -x $AWS_CLOUDWATCH_HOME/bin/mon-get-stats ]; then
	echo 'Cannot execute mon-get-stats. Set env.AWS_CLOUDWATCH_HOME' >&2
	exit 1
fi

TMPFILE=$(mktemp)
if [ ! -w $TMPFILE ]; then
	echo "Cannot write to temp file $TMPFILE" >&2
	exit 1
fi

export AWS_CLOUDWATCH_HOME
export JAVA_HOME

METRICNAME=NetworkIn

$AWS_CLOUDWATCH_HOME/bin/mon-get-stats $METRICNAME -I $AWS_ACCESS_KEY_ID -S $AWS_SECRET_ACCESS_KEY -n $NAMESPACE --dimensions $DIMENSIONS -s Sum --period 300 --start-time $(date --iso-8601=seconds --date="5 minutes ago")  > $TMPFILE

if [ $? -ne 0 ]; then
	echo 'Failed to run mon-get-stats' >&2
	rm $TMPFILE
	exit 1
fi

IN=$(printf %0.f $(echo "($(cat $TMPFILE|awk '{print $3}' | sed -e 's/[eE]+*/\*10\^/')) / 300 * 8"|bc))

METRICNAME=NetworkOut

$AWS_CLOUDWATCH_HOME/bin/mon-get-stats $METRICNAME -I $AWS_ACCESS_KEY_ID -S $AWS_SECRET_ACCESS_KEY -n $NAMESPACE --dimensions $DIMENSIONS -s Sum --period 300 --start-time $(date --iso-8601=seconds --date="5 minutes ago")  > $TMPFILE

if [ $? -ne 0 ]; then
 	echo 'Failed to run mon-get-stats' >&2
	rm $TMPFILE
	exit 1
fi


OUT=$(printf %0.f $(echo "($(cat $TMPFILE|awk '{print $3}' | sed -e 's/[eE]+*/\*10\^/')) / 300 * 8"|bc))


rm $TMPFILE

echo "in.value $IN"
echo "out.value $OUT"

exit 0
