#!/bin/sh

DIMENSIONS=LoadBalancerName=$LBNAME
NAMESPACE=AWS/ELB
METRICNAME=Latency

LBNAME=$(basename $0|grep -P -o '(?<=elb_latency_).*')

if [ -z "$LBNAME" ]; then
	echo 'Cannot read lb name' >&2
	exit 1
fi

case $1 in
	config)
		echo "graph_title $LBNAME request latency"
		echo "graph_vlabel seconds"
		echo "graph_category $NAMESPACE"
		echo 'average.label average'
		echo 'maximum.label maximum'
		exit 0;;
esac

if [ -z "$JAVA_HOME" ]; then
	JAVA_HOME=$(readlink -f $(which java)|grep -P -o '.*(?=/bin/java)')
fi

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
	echo 'AWS ID not specified. Set env.AWS_ACCESS_KEY_ID' >&2
	exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
	echo 'AWS Secret not specified. Set env.AWS_SECRET_ACCESS_KEY' >&2
	exit 1
fi

if [ ! -x $AWS_CLOUDWATCH_HOME/bin/mon-get-stats ]; then
	echo 'Cannot execute mon-get-stats. Set env.AWS_CLOUDWATCH_HOME' >&2
	exit 1
fi

TMPFILE=$(mktemp)
if [ ! -w $TMPFILE ]; then
	echo "Cannot write to temp file $TMPFILE" >&2
	exit 1
fi

export AWS_CLOUDWATCH_HOME
export JAVA_HOME
$AWS_CLOUDWATCH_HOME/bin/mon-get-stats $METRICNAME -I $AWS_ACCESS_KEY_ID -S $AWS_SECRET_ACCESS_KEY -n $NAMESPACE --dimensions $DIMENSIONS -s Average,Maximum --period 300 --start-time $(date --iso-8601=seconds --date="5 minutes ago") > $TMPFILE

cat  $TMPFILE

if [ $? -ne 0 ]; then
	echo 'Failed to run mon-get-stats' >&2
	rm $TMPFILE
	exit 1
fi

AVERAGE=$(cat $TMPFILE|awk '{print $3}'|grep -Po '[0-9]*\.[0-9]{0,2}')
MAXIMUM=$(cat $TMPFILE|awk '{print $4}'|grep -Po '[0-9]*\.[0-9]{0,2}')

rm $TMPFILE

echo "average.value $AVERAGE"
echo "maximum.value $MAXIMUM"

exit 0
